# docker network create spring-cloud-network
version: '3.4'
networks:
  spring-cloud-network:
    external: true
services:
  config-store:
    image: putstack/config-store
    networks:
      - spring-cloud-network
    ports:
      - "9000:80"
    environment:
      - DISCOVERY_URL=http://discovery/eureka

  discovery:
    image: putstack/discovery
    depends_on:
      - config-store
    networks:
      - spring-cloud-network
    ports:
      - "8761:80"
    environment:
      - CONFIG_STORE_URL=http://config-store

  api-gateway:
    image: putstack/api-gateway
    depends_on:
      - config-store
      - discovery
    networks:
      - spring-cloud-network
    ports:
      - "8000:80"
    environment:
      - CONFIG_STORE_URL=http://config-store
      - DISCOVERY_URL=http://discovery/eureka

  order-command:
    image: putstack/order-command
    depends_on:
      - config-store
      - discovery
      - api-gateway
    networks:
      - spring-cloud-network
    ports:
      - "8003:80"
    environment:
      - CONFIG_STORE_URL=http://config-store
      - DISCOVERY_URL=http://discovery/eureka

  order-query:
    image: putstack/order-query
    depends_on:
      - config-store
      - discovery
      - api-gateway
    networks:
      - spring-cloud-network
    ports:
      - "8004:80"
    environment:
      - CONFIG_STORE_URL=http://config-store
      - DISCOVERY_URL=http://discovery/eureka