server:
  port: 8761
logging:
  level:
    root: ERROR
spring:
  application:
    name: discovery_service
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false