spring:
  config:
    activate.on-profile: local
  cloud:
    config:
      uri: ${CONFIG_STORE_URL:http://localhost:9000}
      fail-fast: true
---
spring:
  config:
    activate.on-profile: stage
  cloud:
    config:
      uri: ${CONFIG_STORE_URL:http://localhost:9000}
      fail-fast: true