encrypt:
  key-store:
    alias: apiEncryptionKey
    location: file:///${user.home}/Workspace/Resource/keystore/msaAPIEncryptionKey.jks
    password: storepass1234
signature:
  token:
    expiration: 86400000
    secret: "{cipher}AQCa/Kx34hxcYYhiCVh6ziTczwDKgbliVjXlpanpurxlJ9ofFX8nRr+uKoJIIAwDCXoV+I75DD8YdL1dTfwq+1y3BmTnND/ip8NwC4oi26ujgETFo8it4IMbAdqPRXf25j2sk70FEfkDAZOt4xOdKLfEnrMjDd9MW48Fjzp2/QP8tl3MSANE7DbupvnFNLSEptYXXLqZjH+dRRjfYNs8cF01wEnNGmnEKwCWC2jVJP9M7rNu8LYVi5yw88nx8RFcj7hgXOTwBoUjngTK7SLCh+mmkU4jQMDmAye05FBkXXnAiBVF0r3HgAWI15tWODWmveooC2BQafqfyHt8seF8ShGzF24kiSi2q+6BtG/kttIUNZCbYfypI3sX807HDAnWj90="
rabbitmq:
  host: 127.0.0.2
  port: 5672
  username: guest
  password: "{cipher}AQAfKIFa9IoFeWw0G+MDxpmNW1QD6Gzjxis2w3XdH+yuBEkaGmRD2h4zyG9ZPjCMjPRVNWtLeOVHVOQT/qoGEZOVaiR4IuvSC6hMXTMfPJEEx/dvdlfiaJAfwxYymNhwR+pXH4J1UHbrEdvQyCXWJYU3PXJ3hi5phCORklZFiwaIXyX6mONphtZ9OS2PIbiL7JIYb1radiWwSkGLCdbwM0GVARfM6aCVlbsTN2QrZM1Q3/9LZ0SJ0B0QOsW/IlLg3miOfLZ50+Q1d+6gM8BG+OuXQsGvZY+F8SrSNrAL0+CEufqgA6njfaeFvi8/6mFJdnzfdMD4d4r8gFFQTbIcAv0JMZHs3pmwtLm9qJKDEABFambYlFlz7je1VTohp6ioNmA="
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"