server:
  port: 8000
logging:
  level:
    root: DEBUG
spring:
  cloud:
    gateway:
      # default-filters:
      # - name: GlobalFilter
      #   args:
      #     baseMessage: Spring Cloud Gateway Global Filter
      #     preLogger: true
      #     postLogger: true
      routes:
      # - id: user_service
      #   uri: http://localhost:8002
      #   predicates:
      #   - Path=/users/**z
      - id: order_service_command
        uri: lb://ORDER-SERVICE-COMMAND
        predicates:
          - Path=/order_service/orders/**
          - Method=POST, DELETE, PATCH, PUT
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/order_service/(?<segment>.*), /$\{segment}
      - id: order_service_query
        uri: lb://ORDER-SERVICE-QUERY
        predicates:
          - Path=/order_service/orders/**
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/order_service/(?<segment>.*), /$\{segment}